print("EEEEE  DDDD   U   U     PPPP")
print("E      D   D  U   U     P   P")
print("E      D   D  U   U     P   P")
print("EEE    D   D  U   U     PPPP")
print("E      D   D  U   U     P")
print("E      D   D  U   U     P")
print("EEEEE  DDDD    UUU      P")